import type { Metadata } from 'next'
import { Inter, Fira_Code, Fira_Sans, Agdasima, Fira_Sans_Extra_Condensed, Monoton, Ubuntu_Mono } from 'next/font/google'
import './globals.css'
import Navbar from './Components/Navbar'

const inter = Fira_Sans({ subsets: ['latin'], weight: '400', style: 'normal' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fa" dir='rtl'>
      <body className={inter.className}>
        <Navbar/>
        {children}
      </body>
    </html>
  )
}
